version: '3'
services:
  train:
    image: firdos2345/train:v1
    ports:
      - "81:80"
    deploy:
      replicas: 3

  movie:
    image: firdos2345/movie:v1
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: firdos2345/recharge:v1
    ports:
      - "83:80"
    deploy:
      replicas: 3
